config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope :admin do
    get '/', to: 'admins#index'
    resources :users, except: %I[index new]
  end

  resources :tests, only: %I[create show update]

  root to: 'users#show'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable

  has_many :tests, dependent: :destroy

  validates :full_name, :login, :stored_password, presence: true
  validates_uniqueness_of :login

  PASSWORD_LENGTH = Settings.users.password_len.to_i


  class << self
    def new_self(full_name)
      login = generate_uniq_login
      pass = Devise.friendly_token.first(PASSWORD_LENGTH)
      enc_pass = Encryptor.enc(pass)

      new(full_name: full_name, login: login, password: pass,
          stored_password: enc_pass, password_confirmation: pass)
    end

    private

    def generate_uniq_login
      uniq_id = last.nil? ? '1' : last.id.next

      "#{FFaker::InternetSE.slug}_#{uniq_id}"
    end
  end

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end
end

# == Schema Information
#
# Table name: users
#
#  id                  :bigint           not null, primary key
#  encrypted_password  :string           default(""), not null
#  full_name           :string           default(""), not null
#  login               :string           default(""), not null
#  remember_created_at :datetime
#  stored_password     :string           default(""), not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
# Indexes
#
#  index_users_on_login  (login) UNIQUE
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  http_basic_authenticate_with Settings.ba.to_h.merge(except: :show)
  before_action :authenticate_user!, only: :show
  before_action :find_user, only: %I[edit update destroy]

  # GET /
  def show
    @tests = current_user.tests.order(created_at: :desc)
  end

  # POST /admin/users
  def create
    @user = User.new_self(user_params.to_h['full_name'])
    if @user.save
      redirect_to '/admin', notice: Settings.notices.user_created
    else
      redirect_to '/admin', alert: user_errors
    end
  end

  # GET /admin/users/:id
  def edit; end

  # PUT /admin/users/:id
  def update
    if @user.update(user_params)
      redirect_to '/admin', notice: Settings.notices.user_updated
    else
      redirect_to '/admin', alert: user_errors
    end
  end

  # DELETE /admin/users/:id
  def destroy
    @user.destroy
    if @user.destroyed?
      flash[:notice] = Settings.notices.user_destroyed
    else
      flash[:alert] = user_errors
    end
    redirect_to '/admin'
  end

  private

  def user_errors
    @user.errors.full_messages.to_sentence
  end

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:full_name)
  end
end

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  .log-in-field.person
    = f.input :full_name, label: 'ФИО'
  .create-user-action
    = f.button :submit, 'Применить'

app/views/users/edit.html.haml
%section.admin
  .admin-content.billet
    %h2 Редактирование пользователя
    = render 'users/form'

app/views/users/show.html.haml
%section.test
  .test-content.billet
    .test-navigation
      = button_to 'начать тестирование', tests_path, method: :post, class: 'btn start-test'
      = button_to 'выйти', destroy_user_session_path, method: :delete, class: 'btn exit'
    .test-results
      %h5 Результаты:
      - @tests.each do |test|
        .test-item
          = is_solved?(test)
          = test.correct_answers_percentage.to_s + '%'
          = link_to 'Перейти', test